import type { Metadata } from 'next';
import Link from 'next/link';
import { getTranslations } from 'next-intl/server';
import { db } from '@/lib/db';
import { requireViewer } from '@/lib/session';
import { getRailData, getShellBadges } from '@/lib/shell-data';
import { AppShell } from '@/components/layout/app-shell';
import { relativeTime } from '@/lib/feed';
import { MarkAllRead } from './mark-all-read';

export const metadata: Metadata = { title: 'Notifications' };

/** Real notifications, generated by respects, comments, follows and messages. */
export default async function NotificationsPage() {
  const viewer = await requireViewer();
  const t = await getTranslations();
  const [badges, rails, notifications] = await Promise.all([
    getShellBadges(viewer.id),
    getRailData(viewer),
    db.notification.findMany({
      where: { recipientId: viewer.id },
      orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
      take: 50,
      select: {
        id: true,
        type: true,
        body: true,
        targetUrl: true,
        read: true,
        createdAt: true,
        actor: { select: { handle: true, initials: true, avatarColor: true, avatarUrl: true, } },
      },
    }),
  ]);

  const unread = notifications.filter((n) => !n.read).length;

  return (
    <AppShell viewer={viewer} badges={badges} rails={rails}>
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          gap: 12,
          background: 'var(--card)',
          border: '1px solid var(--card-border)',
          borderRadius: 24,
          padding: '20px 24px',
          boxShadow: 'var(--elev)',
        }}
      >
        <div>
          <h1 style={{ fontFamily: 'var(--font-manrope), Manrope', fontWeight: 800, fontSize: 26, letterSpacing: '-.02em', color: 'var(--ink)', margin: 0 }}>
            {t('notifications')}
          </h1>
          <p style={{ margin: '4px 0 0', fontSize: 14, color: 'var(--mute)' }}>
            {unread === 0 ? 'Nothing new right now.' : `${unread} unread`}
          </p>
        </div>
        {unread > 0 ? <MarkAllRead /> : null}
      </div>

      {notifications.length === 0 ? (
        <div
          style={{
            background: 'var(--card)',
            border: '1px solid var(--card-border)',
            borderRadius: 24,
            padding: 40,
            textAlign: 'center',
            boxShadow: 'var(--elev)',
          }}
        >
          <p style={{ margin: '0 0 6px', font: '700 17px/1.3 var(--font-inter), Inter, sans-serif', color: 'var(--ink)' }}>
            No notifications yet.
          </p>
          <p style={{ margin: 0, fontSize: 15, color: 'var(--body)' }}>
            Post an update or follow a few builders and this fills up.
          </p>
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
          {notifications.map((n) => {
            const inner = (
              <>
                <span
                  style={{
                    width: 42,
                    height: 42,
                    borderRadius: 9999,
                    background: n.actor?.avatarColor ?? 'var(--ink)',
                    color: '#fff',
                    font: '800 15px/1 var(--font-manrope), Manrope',
                    display: 'grid',
                    placeItems: 'center',
                    flexShrink: 0,
                  }}
                >
                  {n.actor?.initials ?? 'TX'}
                </span>
                <div style={{ flex: 1, minWidth: 0 }}>
                  <div style={{ fontSize: 15, lineHeight: 1.45, color: 'var(--ink)' }}>{n.body}</div>
                  <div style={{ fontSize: 12.5, color: 'var(--mute)', marginTop: 4 }}>{relativeTime(n.createdAt)}</div>
                </div>
                {!n.read ? <span style={{ width: 9, height: 9, borderRadius: 9999, background: 'var(--primary)', flexShrink: 0 }} /> : null}
              </>
            );

            const style: React.CSSProperties = {
              display: 'flex',
              alignItems: 'center',
              gap: 14,
              background: n.read ? 'var(--card)' : 'var(--primary-pale)',
              border: '1px solid var(--card-border)',
              borderRadius: 20,
              padding: '16px 18px',
              boxShadow: 'var(--elev)',
            };

            return n.targetUrl ? (
              <Link key={n.id} href={n.targetUrl} style={style}>
                {inner}
              </Link>
            ) : (
              <div key={n.id} style={style}>
                {inner}
              </div>
            );
          })}
        </div>
      )}
    </AppShell>
  );
}
